### ISSUE TITLE
ZynAddSubFX is missing

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2760]
Since this commit I don't have Zyn instrument anymore on Kubuntu 16.04: https://github.com/LMMS/lmms/commit/355f6c28c5a29a0c28c02dba7426d435c29bebd0

**Comment by tresf** [comment]
@karmux from install or from build directory?  Possibly related to https://github.com/LMMS/lmms/pull/2759.

**Comment by karmux** [comment]
@tresf seems to be present under build/plugins directory but when I open LMMS then it's gone. Previous changeset has Zyn in LMMS.

**Comment by karmux** [comment]
@tresf seems to be present under build/plugins but when I open LMMS there is no Zyn.

**Comment by tresf** [comment]
@karmux https://github.com/LMMS/lmms/pull/2759 explains this exact scenario.  It's failing on 12.04 currently, but might be worth cherry-picking.

> improves the execution of LMMS on Linux from the build tree

**Comment by mikobuntu** [comment]
A git pull and build last night had zynaddsubfx and Carla missing after local install. Note I had to use DWANT QT5 flag to get zyn to build. Built on ubuntu 16.04. I can do further analysis tonight if needed.
On 7 May 2016 17:36, Karmo Rosental <notifications@github.com> wrote:@tresf seems to be present under build/plugins directory but when I open LMMS then it's gone. Previous changeset has Zyn in LMMS.

**Comment by mikobuntu** [comment]
OK I did a fresh build around 10 minutes ago ( so I am up to date ) and all seems well, ZynAddSubFX is now present and another issue seems to be fixed for me, where " Show GUI " was crashing LMMS. I will close that issue out now.. thanks :)

**Comment by karmux** [comment]
Fixed in https://github.com/LMMS/lmms/commit/7246c5749195697de8d9070d2e954ccb82579748.

**Comment by DestyNova** [comment]
I still don't see ZynAddSubFX in the instruments list. Checked the `build/plugins/zynaddsubfx` folder, which contained only the following:

* CMakeFiles
* cmake_install.cmake
* Makefile

**Comment by jasp00** [comment]
@DestyNova, this looks like a different issue. According to the lack of files, the plug-in is not compiled. There should be `libZynAddSubFxCore.so`, `libzynaddsubfx.so` and `RemoteZynAddSubFx` under `build/plugins`. Have you installed FLTK development files?

**Comment by DestyNova** [comment]
@jasp00 hey, thanks for the reply. I forgot to update here after discovering yesterday that, indeed, I had to install the package libfltk-1.3-dev (on Ubuntu) before ZynAddSubFx would be built. All is well now :)
