### ISSUE TITLE
Wayland Problem: Alt-Tabbing between LMMS and other applications makes mouse input disappear.

### ISSUE THREAD

**Issue by HummusSamurai** [LMMS/lmms#3466]
I don't have this problem on X11, only Wayland. I'm using Fedora 25.

Reproduce: alt-tabbing between LMMS and other applications disables mouse input.

I can solve this by alt-tabbing back to LMMS and pressing Ctrl + Q to force-quit it.

This doesn't happen when I switch between application using mouse clicking, only through alt-tabbing.

I would be glad to provide more info if I can. I also checked the issues section and didn't find anything addressing Wayland so I have the suspicion that not a lot of devs are using it ;)

**Comment by tresf** [comment]
Fedora's site says Qt4 is not Wayland ready.  Are you on Qt4 or Qt5?

https://fedoraproject.org/wiki/How_to_debug_Wayland_problems

Are you running a compositor?

Does the problem also occur with other Qt apps such as Qt Linguist?

The description sounds more like a keyboard input bug.  Probably best spent hunting 3rd party trackers.

**Comment by tresf** [comment]
Hmm... some more findings... mostly from [a 2015 blog by Martin Graesslin](https://blog.martin-graesslin.com/blog/tag/wayland/page/3).  I'm not sure how much of this has been fixed since this was published.

> ### What’s wrong with QtWayland?
> QtWayland provides a plugin for Wayland clients, but KWin is not a Wayland client: it is the Wayland server. This created some interesting “problems” which we had to workaround in KWin. KWin just doesn’t fit the usecase of QtWayland QPA plugin and it would not be a good idea to change QtWayland in a way that it supports KWin as a first-class citizen – it’s just a too special use case. So let’s look at some of the issues which motivated me to write an own QPA plugin.
> ### Connecting to the Wayland server
> The wayland plugin is meant for Wayland clients and tries to connect to the Wayland server during the creation of the `QGuiApplication`. As KWin is the Wayland server the plugin wants to connect to, we needed to make sure that the Wayland server and the event loop are up and running before constructing the `QGuiApplication`. This added a restriction that we have to monitor the server socket from the main thread.
> ### Blocking roundtrips
> The wayland plugin performs a blocking roundtrip to the Wayland server during startup to wait for all outputs to be announced. But this happens from the main gui thread, in which also the server lives. You can guess what happens: dead-lock. We fixed this one in QtWayland, but the problem was still there: any blocking call from the main gui thread to the Wayland server would freeze KWin. We experienced this with e.g. eglInitialize, startup of dbus services (e.g. `kded`, `kamd`), rendering of Qt internal windows in case the compositor didn’t send the frame rendered yet. Overall I found this aspect way to fragile and consider especially the fact that the server is in the main thread as a problem.
> ### BypassWindowManagerHint
> KWin uses the `Qt::BypassWindowManagerHint` on all it’s windows because this is needed on X11. The hint is X11 specific and doesn’t make much sense on other platforms, so the Wayland plugin doesn’t show such windows at all. That is a valid approach – there is nothing I could say against it. So in KWin we needed to remove the hint for all windows on Wayland.
> [...read more](https://blog.martin-graesslin.com/blog/tag/wayland/page/3)

**Comment by HummusSamurai** [comment]
I recall that I tried compiling against qt5 and had the same problem, but I'll check again now and report in a few minutes.

**Comment by HummusSamurai** [comment]
@tresf Tried a fresh compile against qt5, the problem persists.

I'm not in a hurry to get it fixed -- I guess I can use X11 for LMMS -- but I just thought it worth posting her.  It''s been around on my laptop for about 4 months, ever since Fedora 25 came out with Wayland as default.

**Comment by tresf** [comment]
> This doesn't happen when I switch between application using mouse clicking, only through alt-tabbing.

> > *The description sounds more like a keyboard input bug. Probably best spent hunting 3rd party trackers.*

> I don't see how it can be a keyboard input bug if the mouse input is what's locking.

It was purely speculative.  We should really get a [backtrace](https://github.com/LMMS/lmms/wiki/Debugging-LMMS) to know where the crash is occuring.

So steps to reproduce are (please confirm)
1.  Install Fedora 25.
2. Compile LMMS `master` branch from source with Qt5 support
3. Open LMMS, alt+tab a few times until deadlock occurs?

Some questions:
 * Does the application still respond to keyboard input?
 * Can you navigate the File Menu, by keyboard shortcut still?
 * Is the cursor broken or just not drawing?

And what desktop environment are you running?  I assume either Kde or Gnome3?

**Comment by tresf** [comment]
Also please report if this is reproducible with another Qt5 so (e.g. Qt Linguist) app we can classify this as upstream or not.

**Comment by HummusSamurai** [comment]
@tresf Yes that is true, I had this problem using a fresh Fedora 25, a Qt5 build, and the default Gnome as my Desktop Environment (3.2x, the latest in the stable repos).

The program still responds to keyboard input, but the mouse is A) entirely invisible from the screen and B) the clicks don't register anywhere. It's as if my mouse has been disconnected entirely (or has been sent to /dev/null 😆 ).

So just to confirm, this behaviour is not just in LMMS but across my entire DE.
That is, even if I ALT+TAB to Firefox, Nautilus, etc... The keyboard works and the mouse is broken.
The only way to fix it without restarting is to close LMMS using the keyboard.

I have not tested it with another Qt5 app but I definitely will try to.
I will tag you in the weekend when I update this thread.

**Comment by BaraMGB** [comment]
@HummusSamurai have you tested to disconnect and reconnect your mouse physically from your computer?

**Comment by HummusSamurai** [comment]
@BaraMGB This problem happens on both a touchpad and a mouse, and yes disconnecting/reconnecting does not change anything.

**Comment by HummusSamurai** [comment]
Correction: Mouse is still visible and moving, but clicks do no register anywhere.

**Comment by yohannd1** [comment]
Touching on this again, I made some tests and at least on Niri and KDE Plasma (both Wayland), the issue doesn't seem to be present. I haven't been successful at setting up GNOME here so I can't test there.
Version: `Version 1.3.0-alpha.1.987+5b13887 (Linux/x86_64, Qt 5.15.18, GCC 15.2.1 20260103)` (separate personal branch but up to date with master).
@HummusSamurai would you be willing to try this again and see if the situation has changed?
