### ISSUE TITLE
The selection tool does not delete clips in groups with the delete key

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4602]
Hi guys, how are you ?. as I said in other threads. I have been using lmms lately and while I have used it, I have found some minimal errors. (apparently irrelevant) but that make it more difficult to use in lmms.

Some of these errors have the selection tools.
![selector no borra en grupo modificada](https://user-images.githubusercontent.com/26127693/45774046-fe36ab00-bc19-11e8-85f3-624bf6b63ab0.png)

Both the selection tool, as the selection in all lmms and the selection by pressing '' Ctrl ''. They have errors such as:

1- Multiple clips can not be deleted together with the '' delete '' key. then I have to delete them individually with the mouse wheel.
2- When selecting a piano roll, bb editor or sample track clip, you can not select the desired parts of the clip, which is to select the entire clip.
3- Does not allow individual or group selection in the file browser, I mean, you can not select anything there.
4- You can not select the tracks in the song editor or in the bb editor, which means that you have to delete them from the options menu.
5- A free selection tool is required. The current selection is square or rectangular. the selection is not accurate.
6- In the bb editor it is impossible to select notes in groups, the free selection would be very useful.
7- The piano roll requires a multiple selection tool. here would be quite useful for piano notes
8- The option of inverted selection in all the editors is needed.
9- In the mixer, in '' add effect '', in the chain of effects and in the tray of controllers, there is no selection tool, nor can they be selected in groups by pressing '' Ctrl '', that is, it is impossible the selection. selection in those parts is very necessary, since in some cases it is necessary to eliminate or use many effects.
10- In the automation editor there is no type of selection tool, nor normal, inverted or multiple. Here would be enough to move, copy or delete automation points.

So far are the problems I've seen both the selection tool and the selection in general, maybe they are minimal errors, but they are very annoying and waste time. it does not always work by pressing '' Ctrl ''. Greetings.

**Comment by musikBear** [comment]
@Gabrielxd195  First - Are you on 1.1.3?
Please update to **1.2.0 RC6** (orange buttons) https://lmms.io/download/#windows
Then retry your fail-collection. block-deletes are fixed in RC, so many of your fails are fixed already

**Comment by Gabrielxd195** [comment]
no friend, I am in version 1.2.0 rc6, what happens is that you can not see the title bar. the selection errors are still valid This photo is from lmms is from the latest version, and that is why I put my suggestions.

**Comment by musikBear** [comment]
....Oh dear. Block-deletes are lost in RC6. 
In RC4 it works perfectly. (win 32)
-a re-introduced bug. 😭

**Comment by jibin1573** [comment]
This has been implemented for version 1.3, where pressing the Delete key deletes selected blocks.

Implemented in master via #3649.

**Comment by SecondFlight** [comment]
@jibin1573, thanks for pointing that out.

@Gabrielxd195, do the fixes in #3649 describe your issue?

**Comment by jibin1573** [comment]
This was actually pointed out by @sawuare, when he closed my issue #4470.😀

**Comment by musikBear** [comment]
@jibin1573 
writes: > This has been implemented for version 1.3

I repeat: it works in RC4 win 32

**Comment by tresf** [comment]
> Implemented in master via #3649.

> I repeat: it works in RC4 win 32

@musikBear not on 1.2.0-RC7 for me (MacOS) and that's OK.  We can stage this for 1.3.0.

@BaraMGB #3649 doesn't seem to work properly with Undo.  It gets journaled as multiple events instead of one single event.  Is that desired?

We also need to find a way to refactor this for MacOS.  There's no "DEL" key on a Mac keyboard, we should entertain using Backspace instead.

@Gabrielxd195 please try to keep your bug reports and enhancements filed separately.  Please edit the bug report to reflect that it's "better selection tool behavior" and then use checkboxes to represent each enhancement.  If you don't clean it up, I'll close it out as a duplicate of #3649 as master branch has the issue described in the title working.

For an example of a "meta" issue, please see here: https://github.com/LMMS/lmms/issues/1472

Also, please read #3649 carefully so that you can explicitly mark stuff that's already coded in master.  In the future, if you don't research before filing a bug, we'll close it out.  This tracker can't be used as a dumping ground for every feature request.

**Comment by BaraMGB** [comment]
@tresf as I mentioned in https://github.com/LMMS/lmms/pull/3649 I don't know how to fix the undo system. In the moment I stuck in a other project. I hope I can get back to lmms development in a few weeks.

Btw: I feel https://github.com/LMMS/lmms/pull/3649 could be a good candidate for backporting in 1.2. Working with this in songeditor is so much easier. Of course we should fix the Mac issues at first.

**Comment by tresf** [comment]
> Btw: I feel #3649 could be a good candidate for backporting in 1.2. Working with this in songeditor is so much easier. Of course we should fix the Mac issues at first.

The goal is to get 1.2.0 out the door and offer nightly "1.3.0" releases shortly following.

**Comment by Gabrielxd195** [comment]
> > Implementado en master via [# 3649](https://github.com/LMMS/lmms/pull/3649) .
> 
> > Repito: funciona en RC4 gana 32.
> 
> @musikBear no está en 1.2.0-RC7 para mí (MacOS) y está bien. Podemos poner esto en escena para 1.3.0.
> 
> @BaraMGB [# 3649](https://github.com/LMMS/lmms/pull/3649) no parece funcionar correctamente con Deshacer. Se registra como eventos múltiples en lugar de un solo evento. ¿Es eso deseado? Tampoco funciona con el menú contextual del botón derecho en absoluto. Solo borra el patrón debajo del teclado.
> 
> También necesitamos encontrar una manera de refactorizar esto para MacOS. No hay una tecla "DEL" en un teclado de Mac, deberíamos entretener usando Backspace en su lugar.
> 
> @ Gabrielxd195, por favor, trate de mantener sus informes de errores y mejoras archivados por separado. Edite el informe de errores para reflejar que es "un mejor comportamiento de la herramienta de selección" y luego use las casillas de verificación para representar cada mejora. Si no lo limpia, lo cerraré como un duplicado de [# 3649,](https://github.com/LMMS/lmms/pull/3649) ya que la rama maestra hace que el problema descrito en el título funcione.
> 
> Para ver un ejemplo de un problema "meta", consulte aquí: [# 1472](https://github.com/LMMS/lmms/issues/1472)
> 
> Además, lea con cuidado [# 3649](https://github.com/LMMS/lmms/pull/3649) para poder marcar explícitamente las cosas que ya están codificadas en master. En el futuro, si no investiga antes de presentar un error, lo cerraremos. Este rastreador no se puede usar como vertedero para cada solicitud de función.

Good night. Update my bug report, I hope it meets your expectations. I do not use github nor am I a developer, I just like lmms and I want to cooperate at least giving suggestions. regards

**Comment by Gabrielxd195** [comment]
> > Implemented in master via #3649.
> 
> > I repeat: it works in RC4 win 32
> 
> @musikBear not on 1.2.0-RC7 for me (MacOS) and that's OK. We can stage this for 1.3.0.
> 
> @BaraMGB #3649 doesn't seem to work properly with Undo. It gets journaled as multiple events instead of one single event. Is that desired? It also doesn't work with the right-click context menu at all. Just deletes the pattern under the keyboard.
> 
> We also need to find a way to refactor this for MacOS. There's no "DEL" key on a Mac keyboard, we should entertain using Backspace instead.
> 
> @Gabrielxd195 please try to keep your bug reports and enhancements filed separately. Please edit the bug report to reflect that it's "better selection tool behavior" and then use checkboxes to represent each enhancement. If you don't clean it up, I'll close it out as a duplicate of #3649 as master branch has the issue described in the title working.
> 
> For an example of a "meta" issue, please see here: #1472
> 
> Also, please read #3649 carefully so that you can explicitly mark stuff that's already coded in master. In the future, if you don't research before filing a bug, we'll close it out. This tracker can't be used as a dumping ground for every feature request.

Good night. Update my bug report, I hope it meets your expectations. I do not use github nor am I a developer, I just like lmms and I want to cooperate at least giving suggestions. regards

**Comment by BaraMGB** [comment]
@Gabrielxd195 can you elaborate more what you mean by "free selection in song editor"?

**Comment by Spekular** [comment]
Also
- "Select multiple tracks in the song editor with selection tool or by pressing "Ctrl"." is already fixed in master since #3649 was merged
- I don't think "Select the desired parts of a clip, instead of selecting the entire clip." makes any sense. The only way I can imagine this working is cutting clips at the box selection boundary, whoch sounds terrible imo.
- Nothing under "Beat Bassline" makes sense to me.
- "Multiple selection of midi notes by pressing "Ctrl" inside the piano roll." In my experience, selection shortcuts tend to deselect before making the new selection, and shift+select is used to add a new selection to the existing one. However, isn't ctrl+shift used for inverted selection somewhere in LMMS?
- Automation editor can, imo, be consolidated into "Selection tool in automation editor"
- Sample track section doesn't make sense to me. Selecting parts of a sample seems like the job of the knife tool and/or left/right resize to me (clone the whole clip and then trim, or cut into sections firsrt and then clone the desired one)
- Multiple selection in the file editor doesn't make sense in any usecase I can think of. You can only load one file into AFP/VeSTige/etc., and load one project into an LMMS instance. Automatically creating several new tracks or opening new copies of LMMS to accomodate selecting multiple files doesn't seem like a good idea.

**Comment by musikBear** [comment]
> I don't think "Select the desired parts of a clip, instead of selecting the entire clip." makes any sense. 

Agree. And the right way to go would be a new method to *split the TCO*, then use the normal select.
>  However, isn't ctrl+shift used for inverted selection somewhere in LMMS?

Afaik *inverting selections* has not been implemented

> opening new copies of LMMS to accomodate selecting multiple files doesn't seem like a good idea.

I could see a way to 'borrow' a *named* part in a different file, but that should not lead to fully loading of the 'donor' project. In fact it could be as simple as *read-copy* a specified section in the donor-project-mmp, and a paste in the receiving-project, followed by a reload.

**Comment by zonkmachine** [comment]
> @Gabrielxd195 can you elaborate more what you mean by "free selection in song editor"?

@Gabrielxd195 I wonder this too. What does 'free selection' mean?



>     * However, isn't ctrl+shift used for inverted selection somewhere in LMMS?

@Spekular Maybe you're thinking of `Ctrl + Shift + A`, which deselects all selected notes? Same as `Esc`. I'm testing inverting selection in the Piano Roll Editor and I'm using `Ctrl + Shift + I`.
