### ISSUE TITLE
RC7 ZASFX -lmms-ui PITCH not played as saved

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4721]
OS  : winXP sp3
LMMS RC7

**Issue description:**
The *saved* file-information for changed PITCH is not default replayed. 
Instead the pitch is kept as 0 with 0 spread (default)

**Recreate         :**
I have a file but board wont attach the zipped file :|
Here is a recording:
https://soundcloud.com/musikbear/pitchzasfx
1. LOADED FROM DISK
2. HOW IT WAS SAVED TO DISK

**Factual event/ bug**
I have figured out what happens:
The value that is saved, it not expressed, until the dial (here PITCH) has been altered. *Any* movement at all, will in replay, result in the *correct* value.
I wonder if it can be *this* issue that has made some user claim, that zasfx are 'resetting' itself. I tried with filter and reso -None of these behave in this way.

**Comment by musikBear** [comment]
project file attached

**Comment by musikBear** [comment]
Cant upload zipped here (?) I dropped a demo file on LSP:
https://lmms.io/lsp/?action=show&file=14251

**Comment by zonkmachine** [comment]
^ ```Error: Invalid file:```

**Comment by zonkmachine** [comment]
I see a difference between RC6 and RC7 with this file. I'll try to bisect this.

**Comment by PhysSong** [comment]
Isn't this #3451?

**Comment by musikBear** [comment]
> Isn't this #3451?

at least **very** similar, but the 3451 need to be expanded to be valid for even saving and reopening. In fact if export has taken place *after* reopening the project, then *this* bug is the reason for 3451
I wish i had a project from 1.1.3 where i had manipulated pitch, and could test how that project would load in rc7, but i dont
How is rc6 different?
..Its a rather bad bug, because it changes output of project, with saved pitch-changes  ( afaik *only* in zasfx -i tested 3oc. **That** was not bugged. I need to test Vestige and SF. 303 is also 'different' from std ..patman too)

**Comment by musikBear** [comment]
@PhysSong 
Sadly the bug is in Vestige too

**Comment by tresf** [comment]
Is there a chance this was fixed by https://github.com/LMMS/lmms/commit/f37ca49e6d52886d40858e23acd1d3ed32f97a71?

**Comment by musikBear** [comment]
is f37ca49 in RC8?
RC8 win32 still have the bug, and with same behavior, tested with the test-file above, with was created on RC7.
There for a made a new RC8 testfile but added a VST too
Unfortunately the bug persists for both zasfx and vst, so if f37ca49 is in RC8, it diddent help

**Comment by tresf** [comment]
@musikBear thanks.  No, this is still a problem and yes, I believe it to be the same code as #3451.  I'm merging the two and marking for stable.

**Comment by tresf** [comment]
> It looks like the pitch isn't properly communicated when loading a project, either. 

@softrabbit wrote this two years ago in #3451, btw.

**Comment by tresf** [comment]
Fixed in 04768ee.  @musikBear the next Windows build will have this issue resolved.
