### ISSUE TITLE
Increase GUI contrast in active/inactive buttons

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6047]
The active and inactive buttons feel like very similar, causing difficulties in identifying which one is active.
It would be nice to have a bit more contrast in those buttons' background color.

![image](https://user-images.githubusercontent.com/5563341/121388977-2a824080-c909-11eb-8177-58b1fffe31ea.png)

In the picture, "No" is selected, but it is visually weaker to know.
Pressing SPACE BAR would send ENTER to "No" button.

Obtaining the above dialog/prompt:
LMMS > Ctrl + O > Try to delete an LMMS File.

**Comment by musikBear** [comment]
Not but, but enhancement, and one important one.
There are select-color mistakes in lmms.
One of the more strange is that we use black as text-select color -Everywhere
If the green frame diddent gave it away, would you spot witch name was selected?
![image](https://user-images.githubusercontent.com/6662066/121426552-014aca00-c974-11eb-9204-d2adb997c1bd.png)
Meta-wise this goes under _accessibility_

**Comment by anytizer** [comment]
![image](https://user-images.githubusercontent.com/5563341/162842212-4885ce0f-6727-4646-9b50-5f4e27adc05c.png)
Slightly difficult to determine which tab is currently active.

**Comment by anytizer** [comment]
Also, #6730

**Comment by michaelgregorius** [comment]
The first issue could be fixed by extending the style sheet with a definition for `QPushButton::default`, e.g.:
```
QPushButton::default {
	background-color: #6c757f;
}
```
This would make the dialogues look as follows:
![6047-DefaultButton-DeleteYesNo](https://github.com/LMMS/lmms/assets/9293269/e4348a85-3061-4838-b603-2fa0836806d3)

![6047-DefaultButton-SaveDiscardCancel](https://github.com/LMMS/lmms/assets/9293269/100fe558-1b03-44e2-9878-d6da13ec0c91)

The gray might be a bit too light though because it makes the text less readable.

**Comment by michaelgregorius** [comment]
The second issue about the selection color of the line edit has been fixed with commit 69a35b58 in pull request #5687. Currently it looks as follows:

![6047-QLineEditSelectionColor](https://github.com/LMMS/lmms/assets/9293269/095d9cb8-830b-43c4-a19d-6b41ff962970)

**Comment by musikBear** [comment]
> 

In this case i still have issue seeing the focused button. I would prefer more 'bling' to make it blatantly obvious, like
![image](https://github.com/LMMS/lmms/assets/6662066/1db293ab-ac36-4c4b-a535-a3122f31e040)

Ugly mockup, but i believe its clear.

**Comment by michaelgregorius** [comment]
Here's how it looks if the default button has a green text color.

With the delete dialog I think there's too much green in the icons and text so that it becomes rather confusing:
![6047-TextColorOfDefaultButton](https://github.com/LMMS/lmms/assets/9293269/d6171644-736f-44b8-be2f-649b07bac880)

On the file selection dialog it's too subtle and the default "OK" button look less important than the "Cancel" button:
![6047-TextColorOfDefaultButtonFileSelection](https://github.com/LMMS/lmms/assets/9293269/ad9a0900-a536-43d4-9276-ad441e6f8289)

Although one of the problems is that the icon that's used for "No" and "Cancel" should not be green but red instead.

**Comment by flurick** [comment]
![image](https://github.com/LMMS/lmms/assets/3645797/9ff1484c-955b-4cb2-b60c-2aa9c94dd8f6)

```
QPushButton:focus {
  border: 1px solid lightgreen;
  border-radius: 4px;
  background-color: #17793b;
}
```

**Comment by Rossmaxx** [comment]
@flurick if you don't mind, can you open a PR?

**Comment by musikBear** [comment]
> ...

I like the border ! It shows what button is in focus, bur perhaps 2 px outline would be clearer.
The green button-color is however confusing.
Many would exspect that green would be for a save-button.
In this case the green button would not save anything, but just close, that is not intuitive.

**Comment by Rossmaxx** [comment]
Since flurick has not responded, i decided to take up this one.

**Comment by RoxasKH** [comment]
Leaving here a couple of info/mockups about the issue like that i've talked about in #7202 

> here's a couple of quickly drafted option that take inspiration from other programs, one just changes the selectede button color, the other uses an outer border to give a dvisual difference both in colors and perceived size
> 
> | Colored | Border |
> | -------- | ------- |
> | ![colored](https://github.com/LMMS/lmms/assets/40141826/d7d837f3-afe9-4448-a607-6a3cfb650403) | ![outer-border](https://github.com/LMMS/lmms/assets/40141826/c2d543d7-1c73-4d48-b76c-ebe1336aad51) |
> 
> In the border one, bg color might also gets a little darker, but it should keep the gradient and shouldn't reach the point where it blends in to the background.
> 
> Ps side note: the colored button proposal was also mentioned about making the loop state more evident in https://github.com/LMMS/lmms/issues/3069 , where Rebecca also proposed a darker background/green icon mock-up that could also apply as a possible option here too.
