### ISSUE TITLE
Vestige: Remote plugin 'RemoteVstPlugin32' not found

### ISSUE THREAD

**Issue by hankster112** [LMMS/lmms#6408]
### Bug Summary
Attemping to open a DLL or EXE VST in Vestige produces no response in LMMS except for "Remote plugin '/path/to/RemoteVstPlugin32' not found" when launched via Terminal. Occurs on Devuan 3 Beowulf (Debian fork).

#### Steps to reproduce
Build latest master from 3964c53 with `cmake .. -DCMAKE_INSTALL_PREFIX=/opt/lmms/ -DWANT_VST==ON -DCMAKE_PREFIX_PATH=/usr/lib/wine`
Add Vestige to track and attempt to open DLL or EXE VST, in this case the [Korg M1 VST](https://www.korg.com/us/products/software/kc_m1/).

#### Expected behavior
Vestige loads the VST.

#### Actual behavior
Vestige reads "No VST plugin loaded" and outputs error in console.

#### Screenshot
![image](https://user-images.githubusercontent.com/66497709/169189735-bfdebf93-e643-4153-acf2-7c859a71ab87.png)

#### Affected LMMS versions
Latest from master 3964c53.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

Lv2 plugin SUMMARY: 0 of 0  loaded in 0 msecs.
Cannot load library /opt/lmms/lib/lmms/libcarlapatchbay.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
Cannot load library /opt/lmms/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /opt/lmms/lib/lmms/libcarlarack.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
Remote plugin '/opt/lmms/lib/lmms/32/RemoteVstPlugin32' not found.
</pre>
</details>

Are the libcarla errors relevant?

**Comment by PhysSong** [comment]
What is your Wine version? Also, could you post the output of `grep -i wine CMakeCache.txt` in the build directory?
FYI, The errors related to Carla is not related to VST issues.

**Comment by hankster112** [comment]
wine-7.8 (Staging)

`
CMAKE_PREFIX_PATH:UNINITIALIZED=/usr/lib/wine
WINE_BUILD:FILEPATH=/usr/lib/wine/winebuild
WINE_CXX:FILEPATH=/usr/lib/wine/wineg++
WINE_INCLUDE_DIR:PATH=/usr/include/wine
//Details about finding Wine
FIND_PACKAGE_MESSAGE_DETAILS_Wine:INTERNAL=[/usr/lib/wine/wineg++][/usr/include/wine][v()]
//ADVANCED property for variable: WINE_BUILD
WINE_BUILD-ADVANCED:INTERNAL=1
//ADVANCED property for variable: WINE_CXX
WINE_CXX-ADVANCED:INTERNAL=1
//ADVANCED property for variable: WINE_INCLUDE_DIR
WINE_INCLUDE_DIR-ADVANCED:INTERNAL=1
`

**Comment by hankster112** [comment]
Any update?

**Comment by irrenhaus3** [comment]
I can reproduce this on my setup with wine 5.0 and on current master, sans the `CMAKE_PREFIX_PATH:UNINITIALIZED` output. RemoteVstPlugin64 gets built, RemoteVstPlugin32 does not.  
The reason for that is that detection of `winegcc`s 32bit-capability fails.  
You should see the following warning when running CMake: 
```
CMake Warning at plugins/VstBase/RemoteVstPlugin32.cmake:54 (MESSAGE):
  winegcc fails to complie 32-bit binaries, please make sure you have 32-bit
  GCC libraries
```
That error message needs clarification IMO, the presence of `g++-multilib` on my system doesn't fix it, and the installed `wine64-tools`, which provides `/usr/lib/wine/wineg++` and friends, states to be capable of generating 32bit-binaries. I don't have much of an idea what's going wrong there.

**Comment by irrenhaus3** [comment]
So it turns out, `libwine-dev:i386` was the key here. That one pulls in `libc6-dev:i386 libcrypt-dev:i386 linux-libc-dev:i386`, and thus allows `ld` to find the missing 32bit symbols. Install these and reload your CMake project, and RemoteVstPlugin32 should build as normal.  
@PhysSong: Can you clarify the error message in the cmake file?

**Comment by hankster112** [comment]
I now get a different error when trying to load the VST:
`027c:err:unwind:check_bpf_jit_enable BPF JIT is not enabled in the kernel, enable it to reduce syscall emulation overhead.
0284:err:unwind:check_bpf_jit_enable BPF JIT is not enabled in the kernel, enable it to reduce syscall emulation overhead.
Starting using X11Embed protocol.
malloc(): invalid size (unsorted)
QProcess: Destroyed while process ("/opt/lmms/lib/lmms/32/RemoteVstPlugin32") is still running.
Process error:  QProcess::ProcessError(Crashed)
Remote plugin crashed
`

**Comment by hankster112** [comment]
Still having the same issue, updating to the latest build has not fixed this.

**Comment by mirk0dex** [comment]
I have the same issue on Void GNU/Linux, self-compiled lmms-1.3.0-alpha.1.288+g3440d49aa-linux-x86_64.AppImage (but I had it too on the latest official alpha release).

Wine version: 8.6.

When I open a .dll VST in VeSTige, a dialog box appears in the bottom left corner of the screen, that contains nothing. LMMS freezes for a little while and then nothing has changed. No VST plugin is loaded, VeSTige still shows "No VST plugin loaded".

This is the full terminal log:

`
~ » lmms-1.3.0-alpha.1.288+g3440d49aa-linux-x86_64.AppImage 
Carla appears to be installed on this system at /lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
error: failed to open file /home/[USERNAME OMITTED]/.lv2/DPF-Plugins-v1.5/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/[USERNAME OMITTED]/.lv2/DPF-Plugins-v1.5/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/[USERNAME OMITTED]/.lv2/DPF-Plugins-v1.5/manifest.ttl
error: failed to open file /home/[USERNAME OMITTED]/.lv2/.stfolder/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/[USERNAME OMITTED]/.lv2/.stfolder/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/[USERNAME OMITTED]/.lv2/.stfolder/manifest.ttl
error: failed to open file /usr/local/lib/lv2/LibreMiser.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/LibreMiser.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/LibreMiser.lv2/manifest.ttl
error: failed to open file /home/[USERNAME OMITTED]/.lv2/bitrot.lv2/crush.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/[USERNAME OMITTED]/.lv2/bitrot.lv2/crush.ttl'
Lv2 plugin SUMMARY: 183 of 260  loaded in 1683 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Lv2 Plugins blacklisted: 16 of 260 
  If you want to ignore the blacklist (dangerous!), please set
  environment variable "LMMS_IGNORE_BLACKLIST" to nonempty.
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
wine: failed to start L"Z:\\tmp\\.mount_lmms-1nD35Ze\\usr\\lib\\lmms\\RemoteVstPlugin64.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
Remote plugin did not connect.
Remote plugin '/tmp/.mount_lmms-1nD35Ze/usr/lib/lmms/32/RemoteVstPlugin32' not found.
Remote plugin '/tmp/.mount_lmms-1nD35Ze/usr/lib/lmms/32/RemoteVstPlugin32' not found.

`

Since VeSTige previously worked (about two months ago), I'm guessing the issue could be related to some Wine updates or updates of other software.

If you need me to test anything, I will be at your disposal.

**Comment by BluesM18A1** [comment]
I started experiencing this issue around the time wine 8.0 came out. Downgrading to wine 6.x solves it, but I'd like to find a better solution since not having the latest wine version installed means trouble for other software on my system. (Currently I am using this program via appimage, I will try other means of installing or building master from source)

I had the idea of trying to force it to use a separate wine prefix using an older version that was set up by playonlinux and executing the program with `env PATH="/home/user/.PlayOnLinux/wine/linux-amd64/6.0.1/:$PATH" WINEPREFIX="/home/user/.PlayOnLinux/wineprefix/wine6.0/" /home/user/lmms.AppImage` but that didn't actually get it to work either.

**Comment by luzpaz** [comment]
Is this issue impacted at all by https://github.com/LMMS/lmms/issues/6672#issuecomment-1616318593 ?

**Comment by KNIX3** [comment]
> Is this issue impacted at all by [#6672 (comment)](https://github.com/LMMS/lmms/issues/6672#issuecomment-1616318593) ?

Isn't that unlikely considering that [`a5dc3fe`](https://github.com/LMMS/lmms/commit/a5dc3fee6a5c51065f268cb19f686284752e69da) was pushed in 2020? This bug is not fixed even in the latest git version so I do not think they are related.

**Comment by hankster112** [comment]
I will test it later today with the new commits.

**Comment by jeffbicca** [comment]
I am facing similar issue but when trying to insert an FX ([UJAM Finisher Micro](https://www.ujam.com/finisher/micro/)) in a channel (using lmms current nightly).

Got this same error in logs running lmms in [AV Linux](https://www.bandshed.net/avlinux/) with Wine staging (8.16).

In an old ubuntu 18.10 with wine 4 and with the same build of lmms, the exact same plugin works perfectly. 
So I am here just with @hankster112 and @mirk0dex wondering that this issue might be somewhat related to newer versions of Wine really.

I did some testing trying to extract the AppImage package and overwriting the symlinks to RemoteVstPlugin32.exe.so and RemoteVstPlugin64.exe.so to the "real files" thinking that the issue could be something related to symlinks but unfortunately this didn't solved the issue,... :(

**Comment by kamkamkamkamkamkamkamkam** [comment]
still getting this issue in all AppImage builds of LMMS
```
wine: failed to start L"Z:\\tmp\\.mount_LOMM-pXtAF78\\usr\\lib\\lmms\\32\\RemoteVstPlugin32.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
Remote plugin did not connect.
```
Compiled versions load VSTs just fine.

**Comment by kamkamkamkamkamkamkamkam** [comment]
I just found another workaround. I noticed that Linux native VSTs are not affected by this bug, which means it's possible to bridge Windows VSTs with something like yabridge in order to use them in LMMS (and any other Linux native DAW).
![image](https://github.com/LMMS/lmms/assets/65249472/74423e32-880b-4354-b502-60c4126175a0)

**Comment by Lazerbeak12345** [comment]
I hate to be the guy, but this issue isn't present on a competitor, Ardour (with yabridge) The fact that Ardour doesn't have these sorts of bugs and supports audio native snipping was enough to push me to use it instead. I'll miss LMMS for sure, but if anyone else just actually wants to make music, I'd recommend taking a look, even if it's only for the short-term. (I do believe that LMMS could be more sustainable, long-term).

**Comment by kamkamkamkamkamkamkamkam** [comment]
> I hate to be the guy, but this issue isn't present on a competitor, Ardour (with yabridge) The fact that Ardour doesn't have these sorts of bugs and supports audio native snipping was enough to push me to use it instead. I'll miss LMMS for sure, but if anyone else just actually wants to make music, I'd recommend taking a look, even if it's only for the short-term. (I do believe that LMMS could be more sustainable, long-term).
> 
> I also did try using LMMS with yabridge, and it didn't seem to work. It's an LMMS issue, since it's working perfectly fine with Ardour.

Actually it's not an LMMS issue, since you can clearly see yabridge working fine in the post right above yours so that in particular may be a _you_ issue... but hey do what works for you I guess.

**Comment by Lazerbeak12345** [comment]
I'd love to help provide any debug information if it's useful. I want LMMS to succeed.

My issue with yabridge+LMMS was that the Fedora Linux install of LMMS doesn't allow me to select `.so` files from VeSTige. `.so` is the output format of yabridge for `.dll`-style VSTs (VST2, I think).

**Comment by Rossmaxx** [comment]
Can anyone check if #7620 fixes this issue?

**Comment by Rossmaxx** [comment]
Should be fixed with #7268 but if it ain't, feel free to reopen

**Comment by RiedleroD** [comment]
issue persists for me. Arch Linux 6.15.4, lmms master (344fdd5b1f228117a2587df3e3e833918e525a0f), tested with gcc 15.1.1 and clang 20.1.7. cmake logs are attached in case it helps.

both `lib32-clang` and `lib32-gcc-libs` are installed.

[cmake_clang.log](https://github.com/user-attachments/files/21237782/cmake_clang.log)
[cmake_gcc.log](https://github.com/user-attachments/files/21237781/cmake_gcc.log)

**Comment by RiedleroD** [comment]
did some testing, and it seems that wine stopped including some 32-bit binaries after the WoW64 update maybe? I removed `ERROR_QUIET` from `cmake/modules/CheckWineGcc.cmake:27` and it gave me this output:

```
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/g++ failed
```

seeing the wine_64_flags, I looked into `/usr/lib/wine/` and indeed there was `i386-unix` with nothing inside. Trying to look for a package that contains `/usr/lib/wine/i386-unix/advapi32.a` yielded no results.

**Comment by AppliedEM** [comment]
Having this issue with version 1.2.2 of lmms installed via apt as well.

**Comment by RiedleroD** [comment]
huh, me too (via pacman). it says that it was compiled and packaged on 28 Jul 2025, so it being an issue with wine's new WoW64 mode is quite likely I think.

**Comment by RiedleroD** [comment]
@AppliedEM your issue seems to be #8041 

for what I talked about, I opened #8050 just now since this seems to be separate
