### ISSUE TITLE
[Archlinux] RemoteVstPlugin32 breaks after WoW64 update

### ISSUE THREAD

**Issue by khoidauminh** [LMMS/lmms#8041]
### System Information

Archlinux

### LMMS Version(s)

Any version

### Bug Summary

Since Archlinux transitioned to using wow64 in their wine package, we can no longer load 32bit Windows VSTs on Linux.

### Expected Behaviour

32bit plugins should load normally.

### Steps To Reproduce

1. Ensure the official wine package is installed and of latest version.
2. Launch LMMS and try to open a 32bit VST, e.g. Meowsynth.

LMMS freezes for a moment with this printed in the console:
```
wine: failed to start L"Z:\\kdm\\home\\kdm\\compiled\\lmms.master\\lib\\lmms\\32\\RemoteVstPlugin32.exe.so": c000007b
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
Remote plugin did not connect.
```

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by stianlow** [comment]
For more details regarding latest LMMS  Vestige plugin bugs as it relates to Wine: 

https://bugs.winehq.org/show_bug.cgi?id=58552#c23

**Comment by stianlow** [comment]
For more details regarding workarounds to this issue:

https://bugs.winehq.org/show_bug.cgi?id=58552#c28

@tresf on LMMS Discord recommends nightly builds of AppImage for WoW64 support vs stable releases which lack the WoW64 support (for now) which causes the 32-bit incompatibility of RemoteVstPlugin.

WineHQ dev @rbernon created a working branch with yabridge team months ago to address the WoW64 difficulties that LMMS also faces as part of the cause of this issue: https://github.com/robbert-vdh/yabridge/tree/new-wine10-embedding

LMMS discord team has been updated about the yabridge patches which may lead to a non-workaround solution for LMMS in the near future.  

In the meantime nightly builds of AppImage allow testing against the latest WoW64 supported versions of Wine.

**Comment by tresf** [comment]
> Since Archlinux transitioned to using wow64 in their wine package, we can no longer load 32bit Windows VSTs on Linux.

Hi, please test against nightly.  The bug report says "any version", but this should be fixed on nightly.  We've also patched some unrelated VST bugs here: https://lmms.io/download/pull-request/7987.

**Comment by RiedleroD** [comment]
the issue persists. freezes for a good 30ish seconds, and the output is as follows:

```
[carla-hook.sh] Carla appears to be installed on this system at /usr/lib/carla so we'll use it.
[carla-hook.sh] Preferring the system's "libgobject-2.0.so.0" over the version bundled.
[jack-hook.sh] Jack appears to be installed on this system, so we'll use it.
[wayland-hook.sh] QT_QPA_PLATFORM="wayland" was provided, using.
Lv2 plugin SUMMARY: 232 of 295  loaded in 1713 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Blocked Lv2 Plugins: 16 of 295 
  If you want to enable them (dangerous!), please set
  environment variable "LMMS_ENABLE_BLOCKED_PLUGINS" to nonempty.
Attempting to reconnect output port 0: lmms:master out L1 ->  - Failure
Attempting to reconnect output port 1: lmms:master out R1 ->  - Failure
Attempting to reconnect input port 0:  -> lmms:master in L1 - Failure
Attempting to reconnect input port 1:  -> lmms:master in R1 - Failure
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

then I go to add vestige and select a VST

```
wine: failed to start L"Z:\\tmp\\.mount_lmms-1clmcHF\\usr\\lib\\32\\RemoteVstPlugin32.exe.so": c000007b
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
```

this is where it freezes - after a while it will unfreeze, having not loaded any VST, and print this last line: `Remote plugin did not connect.`

tested with mda piano and meowsynth.

**Comment by RiedleroD** [comment]
also I will note (since it wasn't before) that winegcc fails to invoke for 32-bit wine in cmake when compiling it from source. perhaps I should open a separate issue for that?

**Comment by tresf** [comment]
> also I will note (since it wasn't before) that winegcc fails to invoke for 32-bit wine in cmake when compiling it from source. perhaps I should open a separate issue for that?

If it's a bug with the build system, sure.  I'm not sure what `winegcc fails to invoke for 32-bit wine in cmake` means.  We have a `winegcc` wrapper we use and we use with `winehq-stable` and I don't recall seeing this, so if it's environmental, I'd prefer to not have yet-another bug.


> the issue persists. freezes for a good 30ish seconds, and the output is as follows:

I have no idea why LMMS starts so slow lately, but I consider this unrelated. If it's related to LV2 scanning, @JohannesLorenz might be able to help, but I don't want to take this too off-topic.


> then I go to add vestige and select a VST

Are you running from the nightly appimage?  That's the only version we support here on our tracker.

**Comment by RiedleroD** [comment]
>  I'm not sure what […] means.

it's what cmake says:

```
  * 32-bit Windows host       : winegcc fails to compile 32-bit binaries, please make sure you have 32-bit GCC libraries
```

I was debugging this a while ago and talked more about it in https://github.com/LMMS/lmms/issues/6408#issuecomment-3074347739

> I have no idea why LMMS starts so slow lately

you misunderstood what I meant. it starts in around 3-5 seconds, then I go to select the 32-bit plugin (mda piano or meowsynth in my case) in vestige, at which point LMMS freezes for a while.

> Are you running from the nightly appimage?

yep, I downloaded it when I read your previous comment just to test it.

**Comment by tresf** [comment]
> > I'm not sure what […] means.
> 
> it's what cmake says:
> 
> ```
>   * 32-bit Windows host       : winegcc fails to compile 32-bit binaries, please make sure you have 32-bit GCC libraries
> ```
> 
> I was debugging this a while ago and talked more about it in [#6408 (comment)](https://github.com/LMMS/lmms/issues/6408#issuecomment-3074347739)

Ah, yes that's interesting.  We'll likely need to update our build logic.  Please file a dedicated bug report and we'll milestone accordingly.

I think we'll need to learn from yabridge's efforts.  As always help is greatly appreciated.

**Comment by RiedleroD** [comment]
> Please file a dedicated bug report […] help is greatly appreciated.

opened a new issue #8050 for this - I don't have time nor expertise to fix it myself, but I will do my best to help in debugging

**Comment by tresf** [comment]
@RiedleroD thanks for reporting.  I guess the **new WOW64 mode** is intended to run 32-bit binaries without a dedicated 32-bit compatibility layer in the OS.  This is awesome, but I think we need to rethink how we start these plugins.

@stianlow do you have any knowledge -- perhaps from the yabridge team -- if we can use our 64-bit binary to start a 32-bit VST?

~~If so, we may be able to just use our 64-bit bridge....~~

**Edit:** Tested it on Arch Linux and it doesn't seem to be this easy unfortunately.

<details>
<summary>Click here to show outdated content</summary>

https://github.com/LMMS/lmms/blob/fbac56fdccc615b4efbd43dcb0a45a748e588838/plugins/VstBase/VstPlugin.cpp#L167-L172

The code would look like this:

```diff
+ case ExecutableType::Win32: 
  case ExecutableType::Win64: 
  	tryLoad( REMOTE_VST_PLUGIN_FILEPATH_64 ); // Default: RemoteVstPlugin64 
  	break; 
- case ExecutableType::Win32: 
- 	tryLoad( REMOTE_VST_PLUGIN_FILEPATH_32 ); // Default: 32/RemoteVstPlugin32 
- 	break; 
```

... in regards to how to detect this, we'd likely need to perform some **new WOW64 mode** test on the OS.

Disclaimer, I'm not sure if the above can technically work, just going off of what winqhq published [here](https://bugs.winehq.org/show_bug.cgi?id=58377#c1).

</details>

**Comment by tresf** [comment]
> I think we'll need to learn from yabridge's efforts. As always help is greatly appreciated.

Ouch: https://github.com/robbert-vdh/yabridge/blob/1e826f072ee79b0c1cab7833bed57fcfa11ae4f7/README.md?plain=1#L869

Quoting yabridge:

> ### 32-bit bitbridge
> 
> **The bitbridge functionality is not compatible and likely will never be compatible with Wine's new WoW64 build mode ([Wine #58377](https://bugs.winehq.org/show_bug.cgi?id=58377)).**
> 
> It is also possible to compile a host application for yabridge that's compatible
with 32-bit plugins such as old SynthEdit plugins. This will allow yabridge to
act as a bitbridge, allowing you to run old 32-bit only Windows plugins in a
modern 64-bit Linux plugin host. For this you'll need to have installed the 32
bit versions of the XCB library. This can then be set up as follows:
> 
> ```shell
> # Enable the bitbridge on an existing build
> meson configure build -Dbitbridge=true
> # Or configure a new build from scratch
> meson setup build --buildtype=release --cross-file cross-wine.conf -Dbitbridge=true
> 
> ninja -C build
> ```
> 
> This will produce a second plugin host binary called `yabridge-host-32.exe`.
> Yabridge will detect whether the plugin you're trying to load is 32-bit or
> 64-bit, and will run either the regular version or the `*-32.exe` variant
> accordingly.

**Comment by stianlow** [comment]
> [@stianlow](https://github.com/stianlow) do you have any knowledge -- perhaps from the yabridge team -- if we can use our 64-bit binary to start a 32-bit VST?
> 
> ~If so, we may be able to just use our 64-bit bridge....~

> > I think we'll need to learn from yabridge's efforts. As always help is greatly appreciated.
> 
> Ouch: https://github.com/robbert-vdh/yabridge/blob/1e826f072ee79b0c1cab7833bed57fcfa11ae4f7/README.md?plain=1#L869

Ouch indeed.

I'm still wrapping my head around how to make 32-bit VSTs compatible with Wine's "new WoW64" vs the older way of Shared WoW64 that involves i386 multilib:
https://bugs.winehq.org/show_bug.cgi?id=58377 (winegcc -m32 fails to link when using the new WoW64 mode)

Wine's "new WoW64" was mentioned for 8.0 release but not official until 9.0:
https://gitlab.winehq.org/wine/wine/-/releases/wine-8.0
https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0

However "new WoW64" isn't mentioned by official build instructions (only shared wow64 involving i386 multilib):
https://gitlab.winehq.org/wine/wine/-/wikis/Building-Wine

I recently raised questions about whether "new WoW64" is ready for prime time but may need to bump it to higher visibility to get WineHQ insider response: 
https://bugs.winehq.org/show_bug.cgi?id=58637#c16

To answer your question more directly:

Quoting Julliard (https://bugs.winehq.org/show_bug.cgi?id=58377#c1):
"32-bit ELF dlls cannot be built in new wow64 mode, since the whole idea is to not use 32-bit Unix libraries.

If you want to support new wow64 with a 32-bit binary, the only way is to build it as PE. If you need to make Unix calls you have to create a separate Unix library and use the WINE_UNIX_CALL interface. This is still a work in progress as far as Winelib is concerned though."

This may suggest a sort of limbo state until said Winelib work resolves past WIP state.

**Comment by tresf** [comment]
> If you want to support new wow64 with a 32-bit binary, the only way is to build it as PE. If you need to make Unix calls you have to create a separate Unix library and use the `WINE_UNIX_CALL` interface. This is still a work in progress as far as Winelib is concerned though.

Right, so in layman's terms:
- Drop `winegcc` entirely
- Compile using `mingw` (or similar)
- Use `WINE_UNIX_CALL` for any Linux APIs

In practical terms, however, this does break any 32-bit support for the foreseeable future; fixing this seems to be a considerable undertaking to migrate the ELF binary components into the "WIP" interface.  Furthermore, this places a new `mingw` (or similar) dependency on our Linux builds.

It would be nice if there was a way through wine to build a 64-bit PE that can still communicate with a 32-bit VST, but I believe that would be an anti-pattern for the winehq project.
