### ISSUE TITLE
MIDI import seems to loose tracks

### ISSUE THREAD

**Issue by kmouse** [LMMS/lmms#815]
I downloaded  this midi:
http://www.mediafire.com/download/pzdoigxv83bhiyr/Replacer+-+Song+for+an+Earth+Pony.mid
and imported it into LMMS. It seemed to play fine (albeit with the drums playing as piano) on windows media player. However on LMMS it seems to be missing several tracks, which seem to not have been imported.
I've tried importing other MIDI's, which all work, so I'm not sure why this midi doesn't import correctly.
I'm using LMMS 1.0.2 on windows 7

EDIT: Link to the file via GitHub itself: [Replacer - Song for an Earth Pony.zip](https://github.com/LMMS/lmms/files/15287210/Replacer.-.Song.for.an.Earth.Pony.zip)

**Comment by Umcaruje** [comment]
@softrabbit was this issue fixed by your recent improvements of MIDI importing?

**Comment by musikBear** [comment]
> was this issue fixed by your recent improvements of MIDI importing?
@Umcaruje 
in win32x yes! -eg *this* & 2033 and related can be marked ok for win32x
Closing is to early, because the other OS's need to be confirmed too -right?

**Comment by softrabbit** [comment]
There shouldn't be much OS dependent code in the MIDI import, but it never hurts to confirm on as many systems as possible.

And as for this particular problem file, I won't say anything. Very short notes were dropped previously, now they are imported. Maybe that's why "several tracks" were missing.

**Comment by midi-pascal** [comment]
@softrabbit Agreed. I experienced the problem of missing tracks containing very short notes - especially drums tracks - for a long time. With the Midi import fix, the problem has been solved.
I use Midi Import a lot with Midi type 0 and 1 for re-orchestration on files from various sources and never noticed a missing track since then so, I assume the problem is solved.

**Comment by musikBear** [comment]
@PhysSong If you look at the midi-import fails, then one more fail need to be mentioned
#4728
Eg LMMS cant import MIDI-files made by LMMS midi-export

**Comment by Rossmaxx** [comment]
There has been quite some MIDI related PRs by @Veratil in between. Is there a chance this got fixed in master?

**Comment by michaelgregorius** [comment]
Adding the MIDI file from the original description here so that it does not get lost: [Replacer - Song for an Earth Pony.zip](https://github.com/LMMS/lmms/files/15287210/Replacer.-.Song.for.an.Earth.Pony.zip).

**Comment by michaelgregorius** [comment]
> There has been quite some MIDI related PRs by @Veratil in between. Is there a chance this got fixed in master?

Unfortunately this is not fixed. REAPER import 27 tracks while LMMS from master only imports 3 instrument tracks and 3 automation tracks. Lots of tracks are missing.

Here's a screenshot of REAPER's import:

![815-REAPER-Import](https://github.com/LMMS/lmms/assets/9293269/e4b76acb-4024-4267-bbad-f5e1671a82e2)

And here's LMMS' import:

![815-LMMS-Import](https://github.com/LMMS/lmms/assets/9293269/2badd691-b566-4f68-857c-d58587ee4700)

**Comment by michaelgregorius** [comment]
For anyone interested in looking at this: set break points in `MidiImport::readSMF` and then import the attached file.

**Comment by Veratil** [comment]
LMMS isn't failing to import anything here actually. The way LMMS loads a MIDI currently is that a track is a MIDI channel. Everything is loaded into the `kontakt drums` track since every track is set to channel 0 except for two it looks like.
It sucks, I know. 😞

**Comment by Veratil** [comment]
I have a complete rewrite of MIDI import working on a local branch, removes our need for portsmf or any external library. It can also load "invalid" MIDIs by ignoring some error points which I know my MIDI editor I use to test can't (and I think portsmf doesn't, I forget honestly).

**Comment by michaelgregorius** [comment]
Sounds good! Does it also create individual tracks instead of merging the information?

**Comment by Veratil** [comment]
> Sounds good! Does it also create individual tracks instead of merging the information?

It will load by channel, but we can change that to per track very easily. The reason I haven't created a draft PR yet is because I'm still working out the control channels, which I'm kind of stuck on trying to figure out the best way to do it. Also I'm not 100% certain where I want to organize the files to.

**Comment by michaelgregorius** [comment]
> It will load by channel, but we can change that to per track very easily.

IMO the chance should be used to also fix this issue.

> The reason I haven't created a draft PR yet is because I'm still working out the control channels, which I'm kind of stuck on trying to figure out the best way to do it.

Is it because LMMS' `MidiClip`s do not seem to store this information?

> Also I'm not 100% certain where I want to organize the files to.

Sound like something that should go into the core. The current implementation is a plugin which is kind of strange for a DAW that mainly deals with MIDI and audio.

**Comment by Veratil** [comment]
> > It will load by channel, but we can change that to per track very easily.
> 
> IMO the chance should be used to also fix this issue.

That sounds fine to me, I'll work on changing it to be track based instead.

> > The reason I haven't created a draft PR yet is because I'm still working out the control channels, which I'm kind of stuck on trying to figure out the best way to do it.
> 
> Is it because LMMS' `MidiClip`s do not seem to store this information?

Yes and no, it's mainly there's not a good 1:1 correlation to MIDI CCs and LMMS stuff. At least not clear ones. Either way, discussion on that doesn't belong in this issue. 😁

> > Also I'm not 100% certain where I want to organize the files to.
> 
> Sound like something that should go into the core. The current implementation is a plugin which is kind of strange for a DAW that mainly deals with MIDI and audio.

Oh it's in core, I'm mainly meaning all the gears of the MIDI classes. 🙂

**Comment by michaelgregorius** [comment]
> > > The reason I haven't created a draft PR yet is because I'm still working out the control channels, which I'm kind of stuck on trying to figure out the best way to do it.
> > 
> > 
> > Is it because LMMS' `MidiClip`s do not seem to store this information?
> 
> Yes and no, it's mainly there's not a good 1:1 correlation to MIDI CCs and LMMS stuff. At least not clear ones. Either way, discussion on that doesn't belong in this issue. 😁

Sorry, I don't know where to discuss it elsewhere so I continue here. :wink: I think ideally LMMS should retain all the information in the MIDI clips and push it into the plugins via their APIs when the song is being played. However, if I understand correctly, one of the problems is that LMMS does not even itself have an API that's similar to VST, CLAP, etc. Which also seems to be the reason why it is hard to integrate third party plugins like they are integrated in other DAWs.

So it might be a good first step to retain all information in the MIDI clips and then to check later what to do with it.

> > > Also I'm not 100% certain where I want to organize the files to.
> > 
> > 
> > Sound like something that should go into the core. The current implementation is a plugin which is kind of strange for a DAW that mainly deals with MIDI and audio.
> 
> Oh it's in core, I'm mainly meaning all the gears of the MIDI classes. 🙂

Can't you organize it under `src/core/midi/` with the other stuff?
